### ISSUE TITLE
Fatal error  'Failed to connect to api.mercadopago.com port 443'

### ISSUE THREAD

**Issue by amouratoglou** [mercadopago/cart-woocommerce#102]
H Guys, I have this error message...

What is it? any hints?

Que es? Alguna pista?

> 
Fatal error: Uncaught exception 'MercadoPagoException' with message 'Failed to connect to api.mercadopago.com port 443: Connection timed out' in /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago/sdk/lib/mercadopago.php:879 Stack trace: #0 /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago/sdk/lib/mercadopago.php(976): MPRestClient::exec(Array, '2.2.15') #1 /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago-module.php(215): MPRestClient::get(Array, '2.2.15') #2 /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago/mercadopago-gateway.php(249): WC_WooMercadoPago_Module::get_categories() #3 /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago/mercadopago-gateway.php(112): WC_WooMercadoPago_Gateway->init_form_fields() #4 /home/kq000257/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(105): WC_WooMercadoPago_Gateway->__construct() #5 /home/kq0002 in /home/kq000257/public_html/wp-content/plugins/woo-mercado-pago-module/mercadopago/sdk/lib/mercadopago.php on line 879

**Comment by amouratoglou** [comment]
The problem was related with client hosting -donweb.

**Comment by WowJava** [comment]
@amouratoglou tengo el mismo problema en el mismo hosting donweb. Como lo solucionaste?

**Comment by amouratoglou** [comment]
@WowJava  la única solución que pude encontrar después de hacer cientos de consultas por chat y tickets de soporte, en donde todos y cada uno de ellos me decian cualquier cosa, la unica forma de solucionar el problema del cliente fue mover todo a otro servidor, en este caso los moví a Bluehost, un server de USA que funciona mucho mejor, en bluehost el problema desaparece... donweb es un hosting de mala calidad. Este problema lo tuve en varios proyectos de forma simultánea, todos con el mismo error. Donweb culpa al plugin y dicen cosas sin coherencia alguna... migrarlos afuera, la mejor opción.

**Comment by Mhz250** [comment]
Sigue siendo bluehost una buena solucion a ese problema? yo estoy en siteground, que es de primera y sigo teniendo problemas donde a veces se pierde la coneccion con api.mercadopago.com
Me tienen podrido con esa api de M....

**Comment by Mhz250** [comment]
@amouratoglou estas usando la version 3.0.15 de Mercadopago?

**Comment by amouratoglou** [comment]
@WowJava 

Versión 99999.2.11
https://es.wordpress.org/plugins/woo-mercado-pago-module/
