### ISSUE TITLE
MercadoEnvios no funciona

### ISSUE THREAD

**Issue by venecialopezeto** [mercadopago/cart-woocommerce#124]
Hola, configure el plugin de mercadopago en woocommerce. Tambien esta configurado mercadoenvios en la cuenta de mercadopago.
Agregue las dos opciones de mercadoenvios en Shipping, y configure los productos para que tengan peso y dimensiones, pero cuando voy al carrito, me aparece:
"There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help."
Esta activado el basic checkout solamente. La Shipping Zone es Argentina.
Probé con codigos postales 1414, C1414, C1414CPV y sigue sin funcionar.
Esta es la url del sitio: http://www.traposdivertidos.com.ar/shop/

Como puedo arreglarlo?

**Comment by marianopw** [comment]
Pudiste encontrar solucion a esto?

**Comment by venecialopezeto** [comment]
Hola @marianopw al final usamos este plugin pago, Kijam me lo configuro y ahora funciona!

https://kijam.com/tienda/producto/mercadopago-para-woocommerce/

**Comment by mvconline1** [comment]
Pero tuviste que pagar. Se entiende que la funcionalidad existe y debería funcionar. Me pasa exactamente lo mismo, pero no encuentro el motivo

**Comment by marianopw** [comment]
@mvconline1 al final lo pude hacer andar con el plugin de mercadopago normal. 
Lo que hice fue eliminar todas las zonas y crear una sola que incluya el pais y los distintos tipos de envio.

**Comment by mvconline1** [comment]
Gracias por responder Mariano, 

Ahora lo pude hacer funcionar, pero solo desactivando la opción "Activa los impuestos y los cálculos de impuestos" de la configuración gral de Woocommerce. 

Sin embargo, solo me activa la opción "Mercado Envíos- Normal", no me habilita la express. ¿A vos si?

Tampoco me habilita otros medios de pago aparte de Mercado Pago, por lo que entiendo eso es así si elegimos mercado envíos.

**Comment by marianopw** [comment]
Yo tampoco veo la Express. Lo de los otros medios de pago es como decis. Solo aceptan mercadoenvios si pagan con mercadopago

**Comment by mvconline1** [comment]
Ah malísimo. 

Muchos clientes quieren tener la opción de Mercado Pago, pero también Todo pago o transferencia bancaria (mi tienda es en Woocommerce) Estoy en contacto con un representante de MP, pero no veo que me puedan ayudar. 

En Tienda Nube funciona bien. Debería ser lo mismo para el resto de las integraciones.

**Comment by mvconline1** [comment]
Mariano, lo resolví. 

Me dejó agregar otros medios de envío (Recogida Local, Envío Gratis, Precio Fijo), agregándolos dentro de la misma zona donde tengo configurado Mercado Envíos Normal y Express (yo lo estaba configurando en una zona aparte)

Ahora me quedo de esta forma. Si tuve que aclarar que para ver los otros medios de pago tenían que elegir el precio fijo, sino queda confuso. 

![image](https://user-images.githubusercontent.com/34658795/41070910-b9807fc2-69cb-11e8-8b6c-0761a200c832.png)

Solo me queda saber por que no me aparece la opción de Express.

**Comment by amessbutreal** [comment]
@mvconline1 Hola! estoy buscando hacer lo mismo, necesito tener opción de transferencia bancaria para un producto puntual, pero directamente me salta la opción de mercadopago con mercadoenvios, como lograste configurarlo? gracias!

**Comment by mvconline1** [comment]
Hola @amessbutreal 

Perdón la demora. 

Te cuento que no se como funciona para 1 solo producto, creo que ahí ya estamos hablando de otro tipo de configuración. 

Yo lo que pude hacer es agregar otros medios de pago/envíos aparte de mercado Pago/Mercado Envíos. Tuve que crear todos los medios de envío dentro de una sola zona (Argentina) tal como lo vez en la imagen debajo. 

![image](https://user-images.githubusercontent.com/34658795/42140065-95e13310-7d6f-11e8-8310-c04a0d792264.png)
