### ISSUE TITLE
Payer extra options / statement_descriptor

### ISSUE THREAD

**Issue by sal0m0n** [mercadopago/cart-woocommerce#2]
Hi, great plugin! It looks very similar to Claudio Sanches unofficial version, 

 In my website I'm collecting the user DNI (Venezuelan Cedula), I would like to send it to Mercadopago, how is the correct way to add it into the preferences array (RIF-V, CED-V)?

 Mercadopago api documentation seems like it was changed recently and I cannot find this info anymore.

Also I would like to set my owm statement_descriptor to lets say "MYDOMAIN.COM", Is this still possible?

Thanks

**Comment by matiasgordon** [comment]
Hi @sal0m0n! Thanks for your message.

You can get the identification types supported [here](https://api.mercadolibre.com/sites/MLV/identification_types).

Statement descriptor is not supported in Venezuela.

Best regards,
Matias
