### ISSUE TITLE
Modal not working. MercadoPago Checkout Render insecure response

### ISSUE THREAD

**Issue by Naahuel** [mercadopago/cart-woocommerce#23]
The modal window in the basic checkout is not working. It appears the script isn't loaded because of an HTTPS problem.

![screenshot from 2016-09-28 09-06-38](https://cloud.githubusercontent.com/assets/1612488/18912835/e5b3116a-855a-11e6-9298-497d08504839.png)

**Comment by marcelohama** [comment]
Hi Naahuel,

We had a SSL/DNS issue that has been fixed. Please, test it now if it is working.
Let me know if it has been fixed for you.

Regards!

**Comment by Naahuel** [comment]
Yes, it is working now. Thank you!
