### ISSUE TITLE
[Bug] No se puede actualizar precio al editar producto

### ISSUE THREAD

**Issue by sdmtt** [mercadopago/cart-woocommerce#58]
## Current Behavior
1) Editar un producto siemple/externo
2) Modificar precio
3) Guardar
4) El precio no se actualizó

## Workaround
1) Editar un producto siemple/externo
2) Cambiar el tipo de producto a "Producto recurrente"
3) Modificar precio
4) Cambiar nuevamente a "Producto simple"

## Detailed Description
El input `_regular_price` se duplicó dentro del tab "Producto Recurrente", por lo que al guardar el producto el valor dentro de este campo es el leído por el servidor, ingnorando completamente el campo real definido por WooCommerce.

**Comment by marcelohama** [comment]
Hi there sdmtt,

Thank you very much for notifying this problem.
Indeed, simple products were not properly saved.

Starting from version 2.2.2, I think that this has been resolved. If not, please, let me know.

Best regards!
