### ISSUE TITLE
Mercadopago erro 400 bad request

### ISSUE THREAD

**Issue by vic3636** [mercadopago/cart-woocommerce#59]
When going to checkout, i receive this error in the console api.mercadopago.com/modules/tracking/checkout?token=&referer=https%3A//jimenacocinatienda.com:1 POST https://api.mercadopago.com/modules/tracking/checkout?token=&referer=https%3A//jimenacocinatienda.com 400 (Bad Request)

Any solutions??

**Comment by lcassettai** [comment]
Same issue :-1:

**Comment by marcelohama** [comment]
Guys,

I just update the plugin yesterday, to version 2.2.6.
I've put a watchdog trying to prevent this issue. Please update and try.

Any problems, notify me.

Regards!

**Comment by lcassettai** [comment]
Thanks!
