### ISSUE TITLE
Bank Ticket Printing

### ISSUE THREAD

**Issue by lenz-dev** [mercadopago/cart-woocommerce#68]
There is a way to apply the print ticket link on the thank you page. In version 3.0 the link that existed before I disappeared and does not open a popup with the ticket.

**Comment by lenz-dev** [comment]
I was able to display the print link of the ticket commenting the following excerpt in the mercadopago-ticket-gateway.php file

if ( $used_gateway != 'WC_WooMercadoPagoTicket_Gateway' )
			return;
		$html = '<p>' .
			__( 'Thank you for your order. Please, pay the ticket to get your order approved.', 'woocommerce-mercadopago-module' ) .
		'</p>';*/

**Comment by marcelohama** [comment]
Hi there,

I think it has been solved in version 2.2.6.
Reference: https://wordpress.org/support/topic/bank-ticket-printing/

Regards!
