### ISSUE TITLE
Asking Shipping Metod

### ISSUE THREAD

**Issue by jimbosonido** [mercadopago/cart-woocommerce#7]
Hello, I have a question. The plugin works for me correctly, but when making payment asks me to confirm a shipping address. as I can prevent ask me this information, as this will have on WooCommerce.

Best regards

Jaime

**Comment by guidodipaolo** [comment]
I have the same problem. 
I have written some days ago and i have not answer yet

**Comment by dgarfinkiel** [comment]
Hi Guys, did you get any answer about this issue?. 

Thanks!

**Comment by guidodipaolo** [comment]
Any answer, we are still waiting for it

**Comment by eseeligh** [comment]
Hey guys!
I have the same problem here!
MercadoPago is asking for the shipping method after the last update. Could you check?

**Comment by dgarfinkiel** [comment]
I found a solution for Opencart, but you can try this: 

In mercadopago-gateway.php line 596 replace...

            'shipments' => array(
            	'cost' => (float)$order->get_total_shipping(),
            	'mode' => 'custom',
            	'receiver_address' => array(
            		'zip_code' => $order->shipping_postcode,
            		//'street_number' =>
            		'street_name' => $order->shipping_address_1 . ' ' .
            			$order->shipping_city . ' ' .
            			$order->shipping_state . ' ' .
            			$order->shipping_country,
            		//'floor' =>
            		'apartment' => $order->shipping_address_2
            	)
            ),

for...

            'shipments' => array(
            	),

Hope it works!

**Comment by JorgeAlan** [comment]
Thanks a lot for the suggestion dgarfinkiel

Aparently it works but when you ask for the payment the plugin substract the shipping fee.

**Comment by guidodipaolo** [comment]
It seems that I will have to change to unoficial Carlos Sanches plugin

**Comment by dgarfinkiel** [comment]
Have you try it by removing the "receiver_address" array?

'shipments' => array(
            'cost' => (float)$order->get_total_shipping()
            )
        ),

**Comment by gmatsuoka** [comment]
Hi!

Please use the latest version of the module. This has been resolved! :)
